# services:
#   db:
#     image: mysql:8.0
#     container_name: saas-db
#     restart: unless-stopped
#     networks:
#       - saas-net
#     environment:
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#     ports:
#       - "${DATABASE_PORT_MAPPING:-3307}:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
#       interval: 5s
#       timeout: 5s
#       retries: 20

#   redis:
#     image: redis:7-alpine
#     container_name: saas-redis
#     restart: unless-stopped
#     networks:
#       - saas-net
#     ports:
#       - "${REDIS_PORT:-6379}:6379"
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 5s
#       timeout: 5s
#       retries: 20

#   app:
#     build: .
#     container_name: saas-app
#     restart: unless-stopped
#     depends_on:
#       db:
#         condition: service_healthy
#       redis:
#         condition: service_started
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./uploads:/app/uploads
#     networks:
#       - saas-net
#     env_file:
#       - .env
#     environment:
#       SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
#       SPRING_JPA_HIBERNATE_DDL_AUTO: update
#       SPRING_DATASOURCE_URL: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
#       SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#       SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#       SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
#       SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
#       SPRING_CACHE_TYPE: redis
#       SPRING_FLYWAY_ENABLED: ${SPRING_FLYWAY_ENABLED}
#       SPRING_FLYWAY_URL: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
#       SPRING_FLYWAY_USER: ${SPRING_DATASOURCE_USERNAME}
#       SPRING_FLYWAY_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#       APP_JWT_SECRET: ${APP_JWT_SECRET}
#       APP_EMAIL_FROM: ${APP_EMAIL_FROM}
#       APP_EMAIL_FROM_NAME: ${APP_EMAIL_FROM_NAME}
#       SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
#       SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
#       SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
#       SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
#       SPRING_MAIL_SMTP_AUTH: ${SPRING_MAIL_SMTP_AUTH}
#       SPRING_MAIL_SMTP_TLS: ${SPRING_MAIL_SMTP_TLS}
#       FILE_STORAGE_LOCAL_PATH: /app/uploads

# volumes:
#   db_data:

# networks:
#   saas-net:
#     driver: bridge

